# vim ft=yaml

# After changing this file, check it on:
#   http://yaml-online-parser.appspot.com/

# See doc/travis_notes.txt for some guidelines

language:
  - python
  - cpp

sudo: required

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

# See http://docs.travis-ci.com/user/caching/#pip-cache
cache: pip

compiler: g++

before_install:
#  - mkdir gco_source
  - pip install --upgrade pip

install:
  - pip install -r requirements.txt
  - pip install pytest>=3.1.3 coverage codecov nose

#  - make download  # the download site is down
  - make all
  - make rm

  - python setup.py check -m -s
  - python setup.py build_ext --inplace

script:
  - nosetests gco --with-doctest --verbose
  - nosetests test_examples.py --exe --with-doctest --verbose
  # - pytest --doctest-modules --ignore=setup.py
  - coverage run --source=gco test_examples.py

after_success:
  - codecov --token=1aef0194-048a-4c59-a0d1-9408b924c493
  - coverage report

  - python setup.py install
  - rm -f -r gco
  - python test_examples.py
